<div style="background: #000;
            color: #FFF;
            margin: 0px;
                padding: 10px 0px 20px 0px;
            text-align: center; 
                ">
    <h1>Week 14 Lab</h1>
</div>

In [2]:
# imports

import numpy as np

## Exercise 1

Create the following numpy arrays:
    
a) An array using the following lists (make it interesting if you can)

In [5]:
l = [0,0,0,0,0] 
m = [1,2,3,4,5]

arr = np.array([l,m])

print(arr)
print(arr.ndim)
print(arr.size)
print(arr.shape)

[[0 0 0 0 0]
 [1 2 3 4 5]]
2
10
(2, 5)


b) A 3 x 4 matrix of zeros: 

In [15]:
arr2 = np.zeros((3,4), dtype=int)

print(arr2)
print(arr2.ndim)
print(arr2.size)
print(arr2.shape)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
2
12
(3, 4)


c) A 2 x 4 matrix of zeros and ones of the following format:

[[0,0,1,1], [0,0,1,1]]

(try without using python lists)

In [14]:
a1 = np.zeros((2,2), dtype=int)
a2 = np.ones((2,2), dtype=int)
new_arr = np.hstack((a1, a2))
new_arr

array([[0, 0, 1, 1],
       [0, 0, 1, 1]])

e) A 3 x 4 array from the following numpy array (do not change the already existing code):

In [9]:
r = np.arange(0,12)
# enter your code below
s = r.reshape(3,4)
print(s)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


f) A 1 x 13 array from the following array

look into the `resize` method

In [13]:
n = np.empty(shape=(2,6))
### enter your code below
n.resize(1,13)
print(n)
print(n.shape)

[[-3.10503618e+231 -3.10503618e+231  6.42285340e-323  0.00000000e+000
   0.00000000e+000  0.00000000e+000  0.00000000e+000  0.00000000e+000
   0.00000000e+000  0.00000000e+000  0.00000000e+000  0.00000000e+000
   0.00000000e+000]]
(1, 13)


Using the following array, create an array that consists of the same numbers but squared and in order from smallest to largest

In [16]:
n = np.array([7, 6, 9, 5, 8, 9, 6, 10, 3, 4, 3, 3, 1, 2, 5, 8, 6, 1, 6, 0])
### enter your code below
new_n = n * n
print(new_n)

[ 49  36  81  25  64  81  36 100   9  16   9   9   1   4  25  64  36   1
  36   0]


## Exercise 2

Produce  the array as asked

a) Create a 3x3x3 array with the numbers from 1, 27. Then slice it to produce the 3x3 array in the middle.

In [25]:
# produce 3x3x3 array
n = np.arange(1,28).reshape(3,3,3)
print(n)

# return 3x3 array in middle
n[1]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

b) Create a 3 x 3 array of random numbers. Then slice it to produce the numbers in the 2-index column.

In [32]:
rng = np.random.default_rng(0)
### enter your code below 
n = rng.random((3,3))

two_index_column = n[:,2]
print(two_index_column)

[0.04097352 0.91275558 0.54362499]


c) Create a 3x3x3 array of zeros. Slice a 2x2 array from it and change the values to 1s. Then output the original 3x3x3 with `0`'s and `1`s

In [58]:
# create 3x3x3 array of zeros
n = np.zeros((3,3,3), dtype=int)
print("original 3x3x3 array of zeros:\n", n)
print('--------------------------------')

# slice 2x2 array
n_slice = n[0][0:2, 0:2]
print("2x2 array sliced from 3x3x3 array:\n", n_slice)
print('--------------------------------')

# change values of 2x2 array to 1s
n_slice[:,:] = 1
print("2x2 array after changing values to 1:\n", n_slice)
print('--------------------------------')

# print new values in original 3x3x3 array
print("current values in 3x3x3 array:\n", n)

original 3x3x3 array of zeros:
 [[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
--------------------------------
2x2 array sliced from 3x3x3 array:
 [[0 0]
 [0 0]]
--------------------------------
2x2 array after changing values to 1:
 [[1 1]
 [1 1]]
--------------------------------
current values in 3x3x3 array:
 [[[1 1 0]
  [1 1 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


d) Create an array of all the numbers from 1, 27 (inclusive). Then produce a slice that outputs only the even numbers less than 14.

In [83]:
n = np.arange(1,28)
n[(n < 14) & (n % 2 == 0)]

array([ 2,  4,  6,  8, 10, 12])

## Exercise 3

a) Create an array of all postive integers from 1 to 100.    
b) Reshape it into a 10 x 10 matrix  
c) Remove multiples (so numbers that aren't prime  
d) Output the prime numbers.  

a)

In [91]:
n = np.arange(1,101)
n

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

b) reshape it into a 10 x 10 matrix

In [92]:
n.resize((10,10))
n

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

c) starting with 2 (until you get to sqrt(100) or 10), replace multiples of that number with 0

In [93]:
for i in range(2,11):
    n[(n >= 10) & (n % i == 0)] = 0
    
print(n)

[[ 1  2  3  4  5  6  7  8  9  0]
 [11  0 13  0  0  0 17  0 19  0]
 [ 0  0 23  0  0  0  0  0 29  0]
 [31  0  0  0  0  0 37  0  0  0]
 [41  0 43  0  0  0 47  0  0  0]
 [ 0  0 53  0  0  0  0  0 59  0]
 [61  0  0  0  0  0 67  0  0  0]
 [71  0 73  0  0  0  0  0 79  0]
 [ 0  0 83  0  0  0  0  0 89  0]
 [ 0  0  0  0  0  0 97  0  0  0]]


d) Using a slice, output your prime sieve containing all of the prime numbers less than 0 (be sure to exclude 1 from your slice)

hint: the length of such slice should be `25`

In [94]:
idx = np.nonzero(n > 1)
print(n[idx])
print(n[idx].size)

[ 2  3  4  5  6  7  8  9 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71
 73 79 83 89 97]
29
